tasks:
    installPnpm:
      name: Install PNPM
      command: |
        npm install --yes --global corepack@latest && \
        COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack enable
      triggeredBy:
        - mannual
        - postDevcontainerStart
    installNPMs:
        name: NPM install
        command: pnpm install
        triggeredBy:
          - mannual
          - postDevcontainerStart
        dependsOn:
          - installPnpm
    updateDeps:
      name: Update NPM Dependencies
      command: pnpm update
      triggeredBy:
        - mannual
        - postDevcontainerStart
      dependsOn:
          - installPnpm
          - installNPMs
    hello:
        name: Hello World
        command: |
            echo "Hello, World!"
        triggeredBy:
        - manual
        # - postEnvironmentStart
        # - postDevcontainerStart

services:
    backendExample:
        name: Backend Service Example
        description: Example service simulating a backend
        commands:
            start: |
                echo "Starting backend service..."
                touch /tmp/backend.started
                while true; do
                    sleep 1
                    date
                done
            ready: |
                if [ -f /tmp/backend.started ]; then
                    echo "Backend service is ready"
                    exit 0
                else
                    echo "Backend service is not ready"
                    exit 1
                fi
            # stop: |
            # 	echo "Stopping backend service..."
            # 	rm /tmp/backend.started
            # 	pkill backend
        triggeredBy:
            - postEnvironmentStart
            # - postDevcontainerStart

