---
tasks:
  installPnpm:
    name: Install PNPM
    command: |
      npm install --yes --global corepack@latest && \
      COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack enable
    triggeredBy:
      - manual
      - postDevcontainerStart
  installNPMs:
    name: NPM install
    command: |
      pnpm install
    triggeredBy:
      - manual
      - postDevcontainerStart
    dependsOn:
      - installPnpm
  updateDeps:
    name: Update NPM Dependencies
    command: |
      pnpm update
    triggeredBy:
      - manual
      - postDevcontainerStart
    dependsOn:
      - installPnpm
      - installNPMs
  hello:
    name: Hello World
    command: |
      echo "Hello, World!"
    triggeredBy:
      - manual

